Initial Import to implement once creation procedures.
EiffelSoftware/EiffelStudio pull request #32
Opened 2018-08-16 14:52 UTC by jvelilla

Updated code generation to generate factory funtions when we have
a once procedure as a creation procedure.

Added a validity check {EIFFEL_CLASS_C} to ensure once creation procedures does not
have arguments

2018-08-18 19:04 UTC, kwaxer requested changes

2018-08-18 19:04 UTC, kwaxer commented on Src/Eiffel/eiffel/interface/eiffel_class_c.e
> +	check_once_creation_procedure (ast_b: CLASS_AS)
This code does not work if an inherited once feature is used as a creation procedure.

So, the validity check should be done somewhere else.

Also, the validity rule applies only to once classes, there is no restriction on arguments for once creation procedures in non-once classes.

2018-08-18 19:04 UTC, kwaxer commented on Src/Eiffel/eiffel/interface/feature_i.e
> +				l_byte_code := tmp_opt_byte_server.disk_item (tmp_body_index)
Given that the byte code is generated from scratch, it does not seem reasonable to load it and modify immediately (moreover, it may break code generation for different class types). New BYTE_CODE should be used instead.

2018-08-18 19:04 UTC, kwaxer commented on Src/Eiffel/eiffel/interface/feature_i.e
> +				l_assign.set_target (generate_target_access_factory)
Shouldn't it simply be `...set_target (create {RESULT_B})`?

2018-08-18 19:04 UTC, kwaxer commented on Src/Eiffel/eiffel/interface/feature_i.e
> +				System.removed_log_file.add (class_type, feature_name)
This has been reported already for a creation procedure itself.

2018-08-18 19:04 UTC, kwaxer commented on Src/Eiffel/eiffel/interface/feature_i.e
> +			l_result.set_is_active (True)
This requires discussion and clear definition in the language standard, otherwise the behavior is unclear.

2018-08-18 19:04 UTC, kwaxer commented on Src/Eiffel/eiffel/interface/feature_i.e
> +			create l_result
Why not simply change function result to `CREATION_EXPR_B`?

2018-08-18 19:04 UTC, kwaxer commented on Src/Eiffel/eiffel/interface/feature_i.e
> +				if System.in_final_mode and then System.inlining_on then
It is better to avoid copy-paste (i.e. code duplication) when possible.

2018-08-20 12:56 UTC, jvelilla commented on Src/Eiffel/eiffel/interface/eiffel_class_c.e
> +	check_once_creation_procedure (ast_b: CLASS_AS)
Any suggestion to do the validity check?

2018-10-01 12:54 UTC, closed without merging